In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
print(arr[:10:2])

[1 3 5 7 9]


In [5]:
print(arr[::2])

[ 1  3  5  7  9 11]


In [7]:
newarr = arr.reshape(3,4)
newarr2 = arr.reshape(2,6)

print(newarr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print(newarr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
arr2 = [1,2,]
newarr2 = arr2.reshape(3,3)
print(newarr2)

AttributeError: 'list' object has no attribute 'reshape'

In [11]:
newarr4 = arr.reshape(2,3,2)
print(newarr4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
arr22 = np.array([1,2,3,4,5,6,7,8,9])
print(arr22.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(arr22.reshape(3,3).base)

[1 2 3 4 5 6 7 8 9]


In [27]:
arr33 = np.array([1,2,3,4,5,6,7,8])
arr332 = arr33.reshape(2,2,-1)
print(arr332)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
arr12 = np.array([[1,2,3],[4,5,6]])

newarr31 = arr12.reshape(-1)
print(newarr31)

[1 2 3 4 5 6]


In [29]:
for x in arr12:
  print(x)

[1 2 3]
[4 5 6]


In [30]:
for x in newarr31:
  print(x)

1
2
3
4
5
6


In [31]:
for x in arr12:
  for y in x:
    print(y)

1
2
3
4
5
6


In [33]:
ar1 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

for x in ar1:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [34]:
for x in ar1:
  for y in x:
    for z in y:
      print(z)


1
2
3
4
5
6
7
8
9
10
11
12


In [35]:
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [36]:
ar2 = np.array([1,2,3,4])
for x in np.nditer(ar2, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'
b'4'


In [38]:
# iter with diffferent step size
for x in np.nditer(ar1[:,::2]):
  print(x)

1
2
3
7
8
9


In [47]:
#enumerate iteration using ndenumerate()
print(ar2)
for x in np.ndenumerate(ar2):
  print(x)


[1 2 3 4]
((0,), 1)
((1,), 2)
((2,), 3)
((3,), 4)


In [48]:
for idx, x in np.ndenumerate(ar2):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [55]:
print(ar1)
print()
reshapArr = ar1.reshape(3,4)
print(reshapArr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
for idx, x in np.ndenumerate(reshapArr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12


In [58]:
# join two arrays

arr_1 = np.array([0,1,2])
arr_2 = np.array([3,4,5])

arr_3 = np.concatenate((arr_1, arr_2))

print(arr_3)

[0 1 2 3 4 5]


In [63]:
#Join 2-D arrays

Arr1 = np.array([[1,2],[3,4]])
Arr2 = np.array([[5,6],[7,8]])

Arr3 = np.concatenate((Arr1, Arr2), axis=0)


print(Arr3)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [64]:
Arr4 = np.concatenate((Arr1, Arr2), axis=1)
print(Arr4)

[[1 2 5 6]
 [3 4 7 8]]


In [67]:
# join two arrays with stack() function

Arr5 = np.stack((Arr1, Arr2), axis=1)
print(Arr5)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [68]:
Arrr1 = np.array([1,2,3,4])
Arrr2 = np.array([5,6,7,8])

arrr3 = np.stack((Arrr1, Arrr2), axis=1)

print(arrr3)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [69]:
Arrr1 = np.array([1,2,3,4])
Arrr2 = np.array([5,6,7,8])

arrr3 = np.stack((Arrr1, Arrr2), axis=0)

print(arrr3)

[[1 2 3 4]
 [5 6 7 8]]


In [71]:
#stack along rows
arr_4 = np.hstack((Arrr1, Arrr2))
print(arr_4)

[1 2 3 4 5 6 7 8]


In [72]:
# stack along columns
arr_6 =np.vstack((Arrr1, Arrr2))
print(arr_6)

[[1 2 3 4]
 [5 6 7 8]]


In [73]:
# stack along height (depth)
arr_7 = np.dstack((Arrr1, Arrr2))
print(arr_7)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [82]:
# array split using array_split()
arr_11 = np.array([1,2,3,4,5,6,7,8,9])

arr_12 = np.array_split(arr_11, 3)
arr_13 = np.array_split(arr_11, 9)
arr_14 = np.array_split(arr_11, 10)

print(arr_12)

print(arr_13)

print(arr_14)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9]), array([], dtype=int64)]


In [86]:
print(arr_12)
print('print individual array as below')
print(arr_12[0])
print(arr_12[1])
print(arr_12[2])

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
print individual array as below
[1 2 3]
[4 5 6]
[7 8 9]


In [90]:
# Numpy searching arrays
arr_21 = np.array([ 1,2,3,2,3,4,2,3,4,5,6,7,8,9])
where_3 = np.where(arr_21 == 3)
where_8 = np.where(arr_21 == 8)
print(where_3)
print(where_8)

(array([2, 4, 7]),)
(array([12]),)


In [91]:
# find where values are even
where_even = np.where(arr_21%2 == 0)

print(where_even)

(array([ 1,  3,  5,  6,  8, 10, 12]),)


In [92]:
# find index where values are odd

where_odd = np.where(arr_21%2 ==1)

print(where_odd)

(array([ 0,  2,  4,  7,  9, 11, 13]),)


In [94]:
#search sorted using searchsorted() in Numpy
# we assume the array is already sorted.
arr_31 = np.array([4,5,6,7,8])
search_sort = np.searchsorted(arr_31, 6)
print(search_sort)

2


In [95]:
# search from right side
search_sort_right = np.searchsorted(arr_31, 6, side='right')
print(search_sort_right)

3


In [96]:
x  = np.sort(arr_21)
print(x)

[1 2 2 2 3 3 3 4 4 5 6 7 8 9]


In [100]:
arr41 = np.array([['a','e'], ['b','d'],[1,3],[2,4]])
sorting = np.sort(arr41)
print(sorting)

[['a' 'e']
 ['b' 'd']
 ['1' '3']
 ['2' '4']]


In [105]:
y = np.reshape(arr41, -1)
print(y)
z = np.sort(y)
print(z)

['a' 'e' 'b' 'd' '1' '3' '2' '4']
['1' '2' '3' '4' 'a' 'b' 'd' 'e']


In [109]:
# Numpy filter array
# Getting some elements out of an existing array and creating a new array out of them is called filtering.
# In NumPy, you filter an array using a boolean index list.

arr_51 = np.array([33,38,44,22,27])

filt_51 = [True, False, False, True, True]

newArr = arr_51[filt_51]
print(newArr)

[33 22 27]


In [111]:
filt_arr = []

for element in arr_51:
  if element > 34:
    filt_arr.append(True)
  else:
    filt_arr.append(False)


newArr1 = arr_51[filt_arr]

print(newArr1)

[38 44]


In [10]:

def fizzBuzz(n):
  #n = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
  for i in range(1, n+1):
    if i%3 == 0 and i%5 == 0:
      print('FizzBuzz')
    elif i%3 == 0 and i%5 != 0:
      print('Fizz')
    elif i%5 ==0 and i%3 != 0:
      print('Buzz')
    elif i%3 !=0 or i%5 != 0:
      print(i)
  #return None
fizzBuzz(15)


1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


fizzBuzz
