In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
print(arr[:10:2])

[1 3 5 7 9]


In [5]:
print(arr[::2])

[ 1  3  5  7  9 11]


In [7]:
newarr = arr.reshape(3,4)
newarr2 = arr.reshape(2,6)

print(newarr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print(newarr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
arr2 = [1,2,]
newarr2 = arr2.reshape(3,3)
print(newarr2)

AttributeError: 'list' object has no attribute 'reshape'

In [11]:
newarr4 = arr.reshape(2,3,2)
print(newarr4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
arr22 = np.array([1,2,3,4,5,6,7,8,9])
print(arr22.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(arr22.reshape(3,3).base)

[1 2 3 4 5 6 7 8 9]


In [27]:
arr33 = np.array([1,2,3,4,5,6,7,8])
arr332 = arr33.reshape(2,2,-1)
print(arr332)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
arr12 = np.array([[1,2,3],[4,5,6]])

newarr31 = arr12.reshape(-1)
print(newarr31)

[1 2 3 4 5 6]


In [29]:
for x in arr12:
  print(x)

[1 2 3]
[4 5 6]


In [30]:
for x in newarr31:
  print(x)

1
2
3
4
5
6


In [31]:
for x in arr12:
  for y in x:
    print(y)

1
2
3
4
5
6


In [33]:
ar1 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

for x in ar1:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [34]:
for x in ar1:
  for y in x:
    for z in y:
      print(z)


1
2
3
4
5
6
7
8
9
10
11
12


In [35]:
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [36]:
ar2 = np.array([1,2,3,4])
for x in np.nditer(ar2, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'
b'4'


In [38]:
for x in np.nditer(ar1[:,::2]):
  print(x)

1
2
3
7
8
9
